### ISSUE TITLE
Dolibarr webservices access

### ISSUE THREAD

**Issue by cannaxtract** [GPCsolutions/doliwoo#81]
Bonjour,

J'ai bien installé DoliWoo dans wordpress, et le plugin arrive a se connecter à Dolibarr car l'utilisateur est créé et qu'il y a une indication de detection

Dolibarr version    OK! (Detected v3.8.2) 

Par contre, j'ai eu une fois une commande qui c'est syncronisée, puis plus rien. Comment faire pour trouver où il y a un problème.

Merci d'avance,
Cédric

**Comment by rdoursenaud** [comment]
Bonjour, l'issue tracker n'est pas un forum d'assistance.
Je vous ai adressé une réponse par email à votre récent message.

**Comment by accett** [comment]
Que est que ce?

Sorry. Je ne cest pas parle francois. Just a little of english

**Comment by rdoursenaud** [comment]
You received this message because you subscribed to the project.
I was just closing a support request made in french telling them that the
issue tracker is not a support forum.
Nothing to worry about.

_Raphaël Doursenaud_
Directeur technique (CTO)
Expert certifié en déploiement Google Apps
https://gpcsolutions.fr/raphael-doursenaud-google-apps-certified-deployment-specialist
+33 (0)5 35 53 97 13 - +33 (0)6 68 48 20 10

Le 29 janvier 2016 à 15:53, AcceTT Soluciones Computacionales <
notifications@github.com> a écrit :

> Que est que ce?
> 
> Sorry. Je ne cest pas parle francois. Just a little of english
> El ene 29, 2016 8:05 a.m., "Raphaël Doursenaud" notifications@github.com
> escribió:
> 
> > Bonjour, l'issue tracker n'est pas un forum d'assistance.
> > Je vous ai adressé une réponse par email à votre récent message.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/GPCsolutions/doliwoo/issues/81#issuecomment-176768745>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GPCsolutions/doliwoo/issues/81#issuecomment-176794024
> .

## 

 https://gpcsolutions.fr
https://gpcsolutions.fr
Technopole Hélioparc
2 avenue du Président Pierre Angot
64053 PAU CEDEX 9
SARL GPC.solutions au capital de 7 500 € - R.C.S. PAU 528 995 921
http://wiki.dolibarr.org/index.php/Dolibarr_suppliers_France#GPC.solutions 
http://www.google.com/a/partnersearch/#partner?partner_id=46687933_a0n60000000sqpWAAQ&partner_name=GPC.solutions
